### ISSUE TITLE
Owner status for events

### ISSUE THREAD

**Issue by Jahleel7** [cse442-fall-2019-offering/442projects-teamijwtp#41]
Create an owner status so that only the owner (the person who created the event) can delete the event.

When a person who is not the owner tries deleting an event, they nothing happens.
If the owner pushes the delete button then the event is deleted.

**Comment by Aosaliu** [comment]
UPDATE: Owner Status not needed, original purpose was to allow only the user who created the event, be the only person who could delete it.
